# Generated by Django 3.2.9 on 2021-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='Firstname', max_length=20, null=True)),
                ('secondname', models.CharField(blank=True, db_column='Secondname', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('major', models.CharField(blank=True, db_column='Major', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
